export var metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout(_a) {
    var children = _a.children;
    return <div>{children}</div>;
}
