import { Inter } from "next/font/google";
import Sidebar from "./(main)/_components/sidebar";
import MobileSidebar from "./(main)/_components/mobile-sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Chat with pdf",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <MobileSidebar />
      <div className="flex overflow-y-hidden h-screen">
        <Sidebar />
        {children}
      </div>
    </>
  );
}
