import { Inter } from "next/font/google";
import Sidebar from "./(main)/_components/sidebar";
import MobileSidebar from "./(main)/_components/mobile-sidebar";
const inter = Inter({ subsets: ["latin"] });
export var metadata = {
    title: "Chat with images",
    description: "Generated by create next app",
};
export default function RootLayout(_a) {
    var children = _a.children;
    return (<>
      <MobileSidebar />
      {/* <Navigation /> */}
      <div className="flex overflow-y-hidden  bg-white max-h-screen gap-0  ">
        <Sidebar />
        {children}
      </div>
    </>);
}
