import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
export var metadata = {
    title: "Chat with pdf",
    description: "Generated by create next app",
};
export default function RootLayout(_a) {
    var children = _a.children;
    return (<>
     <div>{children}</div>
    </>);
}
